### ISSUE TITLE
ID decomposition support?

### ISSUE THREAD

**Issue by itsvenu** [AlexandrovLab/SigProfilerSingleSample#10]
Hi Mishu,

as you might have noticed from email from/to Ludmil and you regarding ID6 and SBS3, I'd like to test some hypothesis from our data. I'd like to know if ID decomposition is support in SS module?

Also a bit related question, do you suggest to run SigProfilerExtractor to run on let's say 20 samples?

thanks a lot for the help.

**Comment by mishugeb** [comment]
You can detect indel signature as well using a different parameter for the "sig_database" argument. 

In this case, you need to provide sig_database argument to single_sample function as a pandas dataframe and follow the indications in the function definition. Please find them below:

sig_database: dataframe. This is a signature catalogue where the row index will be the names
of mutations and the column names will be the signature names. The sum of each column
should be one. The row numbers should be equal to the row the number of the mutational
catalogue and the order/sequence of the mutation types should be same as of those in the
mutational catalogue. 

So, in this case, you need to pass a dataframe which will serve as the signature database. You can get it from the COSMIC site. 


Use SigProfilerExtractor for 20 samples: it depends on how many mutations you have. If the average total mutations per sample is low, for say less than 500,  you should use SigProfilerSingleSample.

**Comment by itsvenu** [comment]
Hi Mishu, thanks a lot for the explanation.
