### ISSUE TITLE
gzip VCF files

### ISSUE THREAD

**Issue by ThomasGro** [AlexandrovLab/SigProfilerSingleSample#12]
Hi,
I use a directory of *.vcf.gz as input but get "File format not supported".
I there a possibility to have support for compressed VCF files as input.
Thank you
TG

**Comment by marcos-diazg** [comment]
Hi @ThomasGro,

Thanks a lot for your suggestion and sorry for the late reply. We will definitely consider it for future enhancements of our tool.

Best,
Marcos
