### ISSUE TITLE
Can this tool be used with a different genome?

### ISSUE THREAD

**Issue by kmegq** [AlexandrovLab/SigProfilerSingleSample#15]
Hello,

I am working on calling mutational signatures in dogs, and would like to use this tool. Is there a way to use SigProfilerSingleSample with the CanFam3.1 reference genome?

Thank you!

Best,
Kate

**Comment by marcos-diazg** [comment]
Hi @kmegq,

You can select a different reference genome using the `ref` parameter in the `single_sample` function as described in the README. Make sure to install previously the required reference genome on SigProfilerMatrixGenerator as described [here](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator).

Hope that helps and sorry for the late reply.

Best,
Marcos
