### ISSUE TITLE
SigProfilerSingleSample not used by CNV signature

### ISSUE THREAD

**Issue by Tina610** [AlexandrovLab/SigProfilerSingleSample#18]
Hi，I read the CNV signature paper(s41586-022-04738-6), 
I understand that computing CNV signature requires SigProfilerMatrixGenerator-->SigProfilerExtractor-->SigProfilerSingleSample. I don't know if I got that right...? 
The sigproSS created on "Nov  7 13:33:06 2018", may cannot  run it with CNV signatures

**Comment by marcos-diazg** [comment]
Dear @Tina610,

Thanks for your interest in our tool! As mentioned in previous issues, we are in the process of retiring SigProfilerSingleSample, and we strongly recommend users to use our new [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/) tool, which has support for CNV mutational signatures assignment in the most recent v0.0.8.

I hope this helps, and please reopen the ticket if you have further questions.
