### ISSUE TITLE
DBS and ID mutational signatures?

### ISSUE THREAD

**Issue by timchu90** [AlexandrovLab/SigProfilerSingleSample#2]
Hi,
Thanks for your work on this program. 
I've successfully run this for SBS mutational signatures on my dataset and was wondering..
How do I get results for DBS and ID mutational signatures? 

Thanks,
Tim

**Comment by marcos-diazg** [comment]
Hi @timchu90,

Many thanks for your question and sorry for the late answer. You can actually run SigProfilerSingleSample for DBS and ID mutation contexts, as well as using other custom contexts. In this case you need to provide `sig_database` argument to `single_sample` function as a pandas dataframe and follow the indications in the function definition. Please find them below:

```
sig_database: dataframe. This is signature catalogue where the row index will be the names
of mutations and the column names will be the signature names. The sum of each column
should be one. The row numbers should be equal to the row the number of the mutational
catalogue and the order/sequence of the mutation types should be same as of those in the
mutational catalogue. 
```

Hope this helps and thank you again for your interest,

Marcos
