### ISSUE TITLE
Sigprofiler single sample decomposition profile doesn't match match COSMIC signature database?

### ISSUE THREAD

**Issue by bzhang19** [AlexandrovLab/SigProfilerSingleSample#20]
Hello,

I tried running sigprofiler single sample on just 1 vcf file and when checking the decomposition profile, I got Subs-01, Subs-05 and Subs-55 as signatures. Are they the same as SBS1, SBS5 and SBS55 signatures on COSMIC website or are they novo signatures? Thanks!

**Comment by marcos-diazg** [comment]
Dear @bzhang19,

Thanks for your interest. As mentioned in previous issues, we are in the process of retiring SigProfilerSingleSample, and we strongly recommend users to use our new [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/) tool, which has support for different reference genomes and COSMIC versions. Regarding your question, SigProfilerSingleSample default signature database corresponds to COSMIC v3 and GRCh37.

I hope this helps, and please reopen the ticket if you have further questions.
