### ISSUE TITLE
Can ID signatures be run on vcfs from build 38?

### ISSUE THREAD

**Issue by bzhang19** [AlexandrovLab/SigProfilerSingleSample#21]
Hello! Looking at the COSMIC website, the ID signatures are all derived from build 37. Is it possible to extract COSMIC ID signatures from build 38 vcfs? Thanks for your time!

**Comment by marcos-diazg** [comment]
Hi @bzhang19,

Thanks for reaching out. As explained in the COSMIC Mutational Signatures downloads website (https://cancer.sanger.ac.uk/signatures/downloads/), there is no renormalization available for the reference ID signatures, in contrast to SBS and DBS signatures. However, you can always extract _de novo_ ID signatures from your GRCh38-aligned genomic data using [SigProfilerExtractor](https://github.com/AlexandrovLab/SigProfilerExtractor).

I'll proceed to close this ticket as it's not related to our legacy SigProfilerSingleSample package, but happy to follow up over email (mdiazgay@health.ucsd.edu) if you have further questions.
