### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by Avramis** [AlexandrovLab/SigProfilerSingleSample#23]
Hi
I am trying to run the single sample on the dog genome usign the following commands.

data="/Users/avraam/Desktop/Ismail/Dog/input/"
spss.single_sample(data, "results", ref="dog", exome=False)
and I ge the following error index out of range. (See atachment for more information).

Do you have any suggestions on how to overcme this issue?
Best
Avraam 
[SigProfilerMatrixGenerator_input_dog2023-07-08.err.txt](https://github.com/AlexandrovLab/SigProfilerSingleSample/files/11986834/SigProfilerMatrixGenerator_input_dog2023-07-08.err.txt)
[SigProfilerMatrixGenerator_input_dog2023-07-08.out.txt](https://github.com/AlexandrovLab/SigProfilerSingleSample/files/11986835/SigProfilerMatrixGenerator_input_dog2023-07-08.out.txt)

**Comment by marcos-diazg** [comment]
Hi @Avramis,

This looks like an issue with [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator). Could you please reopen this issue in the corresponding GitHub? Thanks!

**Comment by Avramis** [comment]
Hi @marcos-diazg 
I dont hting the issue is with [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator) 
When I use the data directly with SigProfilerMatrixGenerator it works ok and the matrix is generated. The problem pnly occures when I use Sigprofiler single Samples.

**Comment by marcos-diazg** [comment]
Thanks for your quick reply! Do you have the same version of SigProfilerMatrixGenerator installed in the environment where you are trying to run SigProfilerSingleSample? I would suggest having an independent environment with the latest versions of every tool to avoid issues.

You can also try to run SigProfilerSingleSample directly with the matrix that you get using SigProfilerMatrixGenerator independently.

Also, as mentioned in previous issues, we are in the process of retiring SigProfilerSingleSample, and we strongly recommend users to use our new [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/) tool, which has support for different reference genomes, COSMIC versions, and variant classes.

I hope this helps, and please reopen the ticket if you have further questions.
