### ISSUE TITLE
minimum threshold for reported signatures?

### ISSUE THREAD

**Issue by timchu90** [AlexandrovLab/SigProfilerSingleSample#4]
Hi,

So i've been comparing results from SigProfilerSingleSample to those of deconstructSigs to better get a grasp of what this tool does differently. I notice that the number of reported signatures for SigProfiler are much lower. 

Is there currently a minimum proportion threshold in place for reporting whether a signature exists in SigProfiler? 
If so, what is that threshold?

Is there a way to adjust SigProfiler to report every signature regardless of threshold?

Thanks again!

**Comment by mishugeb** [comment]
Hi SigProfilerSingleSample is not completed yet. We are still benchmarking to optimize the proportion of thresh-holds. Current the thresh-hold for removing weak signatures is under 1% contribution. And thresh-hold for adding strong signatures is above 2.5% contribution.
