### ISSUE TITLE
Missing Subfolders

### ISSUE THREAD

**Issue by pwanj** [AlexandrovLab/SigProfilerSingleSample#6]
Hello,

I ran spss.single_sample() on a bunch of samples. The resulting /VCF/output/ folder is supposed to have 4 sub-folders:TSB, SBS, DBS and ID. But for some samples, few of the subfolders are missing.

Say, for example, sample1 has all 4 output sub-folders, sample2 is missing DBS sub-folder, and sample3 is missing TSB,SBS,DBS sub-folders. Its quite random, there is no pattern and no error. The number of mutations in the input VCF file varies for each sample. Could that be one of the reasons?

Please can you tell me what might be causing this issue and how can I fix it? I would appreciate your help.

Thanks

**Comment by mishugeb** [comment]
I have answered your question through email.
